// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEDoZzCj7yMGfd7hnM0cSuS234OOhbvDM',
    appId: '1:393817612153:web:4184f06243a22f7697d9a8',
    messagingSenderId: '393817612153',
    projectId: 'back2u-74887',
    authDomain: 'back2u-74887.firebaseapp.com',
    storageBucket: 'back2u-74887.firebasestorage.app',
    measurementId: 'G-8WYYM3MFDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTQVPjGvfhstEdMPhul7QFYzQBtlUI8jI',
    appId: '1:393817612153:android:3af7fe1d90e1360597d9a8',
    messagingSenderId: '393817612153',
    projectId: 'back2u-74887',
    storageBucket: 'back2u-74887.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEefpDmJSOKjGDB3S6IKtz43_x9PdD_hU',
    appId: '1:393817612153:ios:ca35e44bfa5621b897d9a8',
    messagingSenderId: '393817612153',
    projectId: 'back2u-74887',
    storageBucket: 'back2u-74887.firebasestorage.app',
    iosClientId: '393817612153-mint1mf6d4i6v4c6tceur2thg04qaqoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.back2u',
  );

}